name: CI

on: 
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Run linter and formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run format-fix
      - name: ESLint
        run: npm run lint-fix
      - name: Unit tests
        run: npm test
