name: Version

on: 
  pull_request:
    branches:
      -main

jobs:
  version:
    name: Check for Version Bump
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Package JSON Version Check
      - uses: gfellerph/package-json-version-check@v1.0.0-alpha.2

      - name: Bump Version
      - uses: remorses/bump-version@v8
        with: 
          version_file: ./package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
